Repository paketo-buildpacks/sap-machine, pull requests merged in 2022-02, with the labels that each got.

#148 fix: remove reference to JDK 8
  README.md
Labels: semver:patch, type:documentation

#149 Bump libpak to 1.58.0 and libjvm to 1.35.0
  go.mod
  go.sum
Labels: type:dependency-upgrade, semver:minor

#152 Bumped go to 1.17 and added module version
  go.mod
  go.sum
Labels: type:dependency-upgrade, semver:minor

#153 Added module version
  go.mod
  scripts/build.sh
Labels: semver:patch, type:enhancement
