Repository paketo-buildpacks/sap-machine, pull requests merged in 2024-04, with the labels that each got.

#365 Document BPL_JVM_CLASS_ADJUSTMENT
  README.md
Labels: semver:patch, type:documentation

#373 Add Java 22
  .github/pipeline-descriptor.yml
  .github/workflows/pb-update-jdk-22.yml
  .github/workflows/pb-update-jre-22.yml
  .gitignore
  buildpack.toml
Labels: semver:minor, type:enhancement

#383 Fix Java 22 wrong metadata
  buildpack.toml
Labels: type:bug, semver:patch

#384 Add Arm64 support to SAP Machine
  .github/pipeline-descriptor.yml
  .github/workflows/pb-update-jdk-11-arm-64.yml
  .github/workflows/pb-update-jdk-17-arm-64.yml
  .github/workflows/pb-update-jdk-21-arm-64.yml
  .github/workflows/pb-update-jdk-22-arm-64.yml
  .github/workflows/pb-update-jre-11-arm-64.yml
  .github/workflows/pb-update-jre-17-arm-64.yml
  .github/workflows/pb-update-jre-21-arm-64.yml
  .github/workflows/pb-update-jre-22-arm-64.yml
  README.md
  buildpack.toml
  scripts/build.sh
Labels: semver:minor, type:enhancement

#410 Fix the include file for the new dualarch reality
  buildpack.toml
Labels: type:bug, semver:patch
